// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: cosmos/evm/feesponsor/v1/tx.proto

package feesponsorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_SetFeePayer_FullMethodName    = "/cosmos.evm.feesponsor.v1.Msg/SetFeePayer"
	Msg_RemoveFeePayer_FullMethodName = "/cosmos.evm.feesponsor.v1.Msg/RemoveFeePayer"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// SetFeePayer defines a governance operation for setting the EVM fee payer.
	// The authority is hard-coded to the Cosmos SDK x/gov module account.
	SetFeePayer(ctx context.Context, in *MsgSetFeePayer, opts ...grpc.CallOption) (*MsgSetFeePayerResponse, error)
	// RemoveFeePayer defines a governance operation for removing the EVM fee payer.
	// The authority is hard-coded to the Cosmos SDK x/gov module account.
	RemoveFeePayer(ctx context.Context, in *MsgRemoveFeePayer, opts ...grpc.CallOption) (*MsgRemoveFeePayerResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SetFeePayer(ctx context.Context, in *MsgSetFeePayer, opts ...grpc.CallOption) (*MsgSetFeePayerResponse, error) {
	out := new(MsgSetFeePayerResponse)
	err := c.cc.Invoke(ctx, Msg_SetFeePayer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RemoveFeePayer(ctx context.Context, in *MsgRemoveFeePayer, opts ...grpc.CallOption) (*MsgRemoveFeePayerResponse, error) {
	out := new(MsgRemoveFeePayerResponse)
	err := c.cc.Invoke(ctx, Msg_RemoveFeePayer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// SetFeePayer defines a governance operation for setting the EVM fee payer.
	// The authority is hard-coded to the Cosmos SDK x/gov module account.
	SetFeePayer(context.Context, *MsgSetFeePayer) (*MsgSetFeePayerResponse, error)
	// RemoveFeePayer defines a governance operation for removing the EVM fee payer.
	// The authority is hard-coded to the Cosmos SDK x/gov module account.
	RemoveFeePayer(context.Context, *MsgRemoveFeePayer) (*MsgRemoveFeePayerResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) SetFeePayer(context.Context, *MsgSetFeePayer) (*MsgSetFeePayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetFeePayer not implemented")
}
func (UnimplementedMsgServer) RemoveFeePayer(context.Context, *MsgRemoveFeePayer) (*MsgRemoveFeePayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFeePayer not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_SetFeePayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetFeePayer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetFeePayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SetFeePayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetFeePayer(ctx, req.(*MsgSetFeePayer))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RemoveFeePayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRemoveFeePayer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RemoveFeePayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RemoveFeePayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RemoveFeePayer(ctx, req.(*MsgRemoveFeePayer))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.evm.feesponsor.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetFeePayer",
			Handler:    _Msg_SetFeePayer_Handler,
		},
		{
			MethodName: "RemoveFeePayer",
			Handler:    _Msg_RemoveFeePayer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/evm/feesponsor/v1/tx.proto",
}
