// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/evm/feesponsor/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgSetFeePayer defines a message for setting the EVM fee payer.
type MsgSetFeePayer struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// evm_fee_payer is the address that will pay for EVM transaction fees
	EvmFeePayer string `protobuf:"bytes,2,opt,name=evm_fee_payer,json=evmFeePayer,proto3" json:"evm_fee_payer,omitempty"`
}

func (m *MsgSetFeePayer) Reset()         { *m = MsgSetFeePayer{} }
func (m *MsgSetFeePayer) String() string { return proto.CompactTextString(m) }
func (*MsgSetFeePayer) ProtoMessage()    {}
func (*MsgSetFeePayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d57ca0440ca912, []int{0}
}
func (m *MsgSetFeePayer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetFeePayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetFeePayer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetFeePayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetFeePayer.Merge(m, src)
}
func (m *MsgSetFeePayer) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetFeePayer) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetFeePayer.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetFeePayer proto.InternalMessageInfo

func (m *MsgSetFeePayer) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgSetFeePayer) GetEvmFeePayer() string {
	if m != nil {
		return m.EvmFeePayer
	}
	return ""
}

// MsgSetFeePayerResponse defines the response for MsgSetFeePayer.
type MsgSetFeePayerResponse struct {
}

func (m *MsgSetFeePayerResponse) Reset()         { *m = MsgSetFeePayerResponse{} }
func (m *MsgSetFeePayerResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetFeePayerResponse) ProtoMessage()    {}
func (*MsgSetFeePayerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d57ca0440ca912, []int{1}
}
func (m *MsgSetFeePayerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetFeePayerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetFeePayerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetFeePayerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetFeePayerResponse.Merge(m, src)
}
func (m *MsgSetFeePayerResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetFeePayerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetFeePayerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetFeePayerResponse proto.InternalMessageInfo

// MsgRemoveFeePayer defines a message for removing the EVM fee payer.
type MsgRemoveFeePayer struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
}

func (m *MsgRemoveFeePayer) Reset()         { *m = MsgRemoveFeePayer{} }
func (m *MsgRemoveFeePayer) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveFeePayer) ProtoMessage()    {}
func (*MsgRemoveFeePayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d57ca0440ca912, []int{2}
}
func (m *MsgRemoveFeePayer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveFeePayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveFeePayer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveFeePayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveFeePayer.Merge(m, src)
}
func (m *MsgRemoveFeePayer) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveFeePayer) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveFeePayer.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveFeePayer proto.InternalMessageInfo

func (m *MsgRemoveFeePayer) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

// MsgRemoveFeePayerResponse defines the response for MsgRemoveFeePayer.
type MsgRemoveFeePayerResponse struct {
}

func (m *MsgRemoveFeePayerResponse) Reset()         { *m = MsgRemoveFeePayerResponse{} }
func (m *MsgRemoveFeePayerResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveFeePayerResponse) ProtoMessage()    {}
func (*MsgRemoveFeePayerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d57ca0440ca912, []int{3}
}
func (m *MsgRemoveFeePayerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveFeePayerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveFeePayerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveFeePayerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveFeePayerResponse.Merge(m, src)
}
func (m *MsgRemoveFeePayerResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveFeePayerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveFeePayerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveFeePayerResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSetFeePayer)(nil), "cosmos.evm.feesponsor.v1.MsgSetFeePayer")
	proto.RegisterType((*MsgSetFeePayerResponse)(nil), "cosmos.evm.feesponsor.v1.MsgSetFeePayerResponse")
	proto.RegisterType((*MsgRemoveFeePayer)(nil), "cosmos.evm.feesponsor.v1.MsgRemoveFeePayer")
	proto.RegisterType((*MsgRemoveFeePayerResponse)(nil), "cosmos.evm.feesponsor.v1.MsgRemoveFeePayerResponse")
}

func init() { proto.RegisterFile("cosmos/evm/feesponsor/v1/tx.proto", fileDescriptor_e3d57ca0440ca912) }

var fileDescriptor_e3d57ca0440ca912 = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4c, 0xce, 0x2f, 0xce,
	0xcd, 0x2f, 0xd6, 0x4f, 0x2d, 0xcb, 0xd5, 0x4f, 0x4b, 0x4d, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0xce,
	0x2f, 0xd2, 0x2f, 0x33, 0xd4, 0x2f, 0xa9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x80,
	0x28, 0xd1, 0x4b, 0x2d, 0xcb, 0xd5, 0x43, 0x28, 0xd1, 0x2b, 0x33, 0x94, 0x12, 0x4c, 0xcc, 0xcd,
	0xcc, 0xcb, 0xd7, 0x07, 0x93, 0x10, 0xc5, 0x52, 0xe2, 0x50, 0xf3, 0x72, 0x8b, 0xd3, 0x41, 0x86,
	0xe4, 0x16, 0xa7, 0x43, 0x25, 0x24, 0x21, 0x12, 0xf1, 0x60, 0x9e, 0x3e, 0xd4, 0x48, 0x30, 0x47,
	0x69, 0x0b, 0x23, 0x17, 0x9f, 0x6f, 0x71, 0x7a, 0x70, 0x6a, 0x89, 0x5b, 0x6a, 0x6a, 0x40, 0x62,
	0x65, 0x6a, 0x91, 0x90, 0x19, 0x17, 0x67, 0x62, 0x69, 0x49, 0x46, 0x7e, 0x51, 0x66, 0x49, 0xa5,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0xa7, 0x93, 0xc4, 0xa5, 0x2d, 0xba, 0x22, 0x50, 0x7d, 0x8e, 0x29,
	0x29, 0x45, 0xa9, 0xc5, 0xc5, 0xc1, 0x25, 0x45, 0x99, 0x79, 0xe9, 0x41, 0x08, 0xa5, 0x42, 0x36,
	0x5c, 0xbc, 0xa9, 0x65, 0xb9, 0xf1, 0x69, 0xa9, 0xa9, 0xf1, 0x05, 0x20, 0x83, 0x24, 0x98, 0x08,
	0xe8, 0xe5, 0x4e, 0x2d, 0xcb, 0x85, 0xd9, 0x6a, 0xa5, 0xd3, 0xf4, 0x7c, 0x83, 0x16, 0xc2, 0xb4,
	0xae, 0xe7, 0x1b, 0xb4, 0x24, 0x91, 0xc2, 0x07, 0xd5, 0x8d, 0x4a, 0x12, 0x5c, 0x62, 0xa8, 0x22,
	0x41, 0x90, 0xb0, 0x49, 0x55, 0xaa, 0xe1, 0x12, 0xf4, 0x2d, 0x4e, 0x0f, 0x4a, 0xcd, 0xcd, 0x2f,
	0x4b, 0xa5, 0xd4, 0x4b, 0x56, 0xfa, 0x98, 0x8e, 0x92, 0x41, 0x75, 0x14, 0xaa, 0x45, 0x4a, 0xd2,
	0x5c, 0x92, 0x18, 0x82, 0x30, 0xa7, 0x19, 0xbd, 0x66, 0xe4, 0x62, 0xf6, 0x2d, 0x4e, 0x17, 0xca,
	0xe4, 0xe2, 0x46, 0x0e, 0x6f, 0x0d, 0x3d, 0x5c, 0x91, 0xac, 0x87, 0xea, 0x47, 0x29, 0x03, 0x62,
	0x55, 0xc2, 0xac, 0x14, 0x2a, 0xe2, 0xe2, 0x43, 0x0b, 0x0a, 0x6d, 0xbc, 0x66, 0xa0, 0x2a, 0x96,
	0x32, 0x26, 0x41, 0x31, 0xcc, 0x4e, 0x29, 0xd6, 0x86, 0xe7, 0x1b, 0xb4, 0x18, 0x9d, 0x9c, 0x4e,
	0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e, 0xf1, 0xc1, 0x23, 0x39, 0xc6, 0x09, 0x8f, 0xe5, 0x18,
	0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1, 0x58, 0x8e, 0x21, 0x4a, 0x23, 0x3d, 0xb3, 0x24, 0xa3, 0x34,
	0x49, 0x2f, 0x39, 0x3f, 0x57, 0x1f, 0x29, 0x34, 0x2b, 0x90, 0x33, 0x41, 0x49, 0x65, 0x41, 0x6a,
	0x71, 0x12, 0x1b, 0x38, 0x91, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x17, 0xb3, 0x3f, 0xb9,
	0x2a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// SetFeePayer defines a governance operation for setting the EVM fee payer.
	// The authority is hard-coded to the Cosmos SDK x/gov module account.
	SetFeePayer(ctx context.Context, in *MsgSetFeePayer, opts ...grpc.CallOption) (*MsgSetFeePayerResponse, error)
	// RemoveFeePayer defines a governance operation for removing the EVM fee payer.
	// The authority is hard-coded to the Cosmos SDK x/gov module account.
	RemoveFeePayer(ctx context.Context, in *MsgRemoveFeePayer, opts ...grpc.CallOption) (*MsgRemoveFeePayerResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SetFeePayer(ctx context.Context, in *MsgSetFeePayer, opts ...grpc.CallOption) (*MsgSetFeePayerResponse, error) {
	out := new(MsgSetFeePayerResponse)
	err := c.cc.Invoke(ctx, "/cosmos.evm.feesponsor.v1.Msg/SetFeePayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RemoveFeePayer(ctx context.Context, in *MsgRemoveFeePayer, opts ...grpc.CallOption) (*MsgRemoveFeePayerResponse, error) {
	out := new(MsgRemoveFeePayerResponse)
	err := c.cc.Invoke(ctx, "/cosmos.evm.feesponsor.v1.Msg/RemoveFeePayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// SetFeePayer defines a governance operation for setting the EVM fee payer.
	// The authority is hard-coded to the Cosmos SDK x/gov module account.
	SetFeePayer(context.Context, *MsgSetFeePayer) (*MsgSetFeePayerResponse, error)
	// RemoveFeePayer defines a governance operation for removing the EVM fee payer.
	// The authority is hard-coded to the Cosmos SDK x/gov module account.
	RemoveFeePayer(context.Context, *MsgRemoveFeePayer) (*MsgRemoveFeePayerResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SetFeePayer(ctx context.Context, req *MsgSetFeePayer) (*MsgSetFeePayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetFeePayer not implemented")
}
func (*UnimplementedMsgServer) RemoveFeePayer(ctx context.Context, req *MsgRemoveFeePayer) (*MsgRemoveFeePayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFeePayer not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SetFeePayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetFeePayer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetFeePayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.evm.feesponsor.v1.Msg/SetFeePayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetFeePayer(ctx, req.(*MsgSetFeePayer))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RemoveFeePayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRemoveFeePayer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RemoveFeePayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.evm.feesponsor.v1.Msg/RemoveFeePayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RemoveFeePayer(ctx, req.(*MsgRemoveFeePayer))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.evm.feesponsor.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetFeePayer",
			Handler:    _Msg_SetFeePayer_Handler,
		},
		{
			MethodName: "RemoveFeePayer",
			Handler:    _Msg_RemoveFeePayer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/evm/feesponsor/v1/tx.proto",
}

func (m *MsgSetFeePayer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetFeePayer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetFeePayer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EvmFeePayer) > 0 {
		i -= len(m.EvmFeePayer)
		copy(dAtA[i:], m.EvmFeePayer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EvmFeePayer)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetFeePayerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetFeePayerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetFeePayerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRemoveFeePayer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveFeePayer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveFeePayer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRemoveFeePayerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveFeePayerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveFeePayerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSetFeePayer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.EvmFeePayer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSetFeePayerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRemoveFeePayer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRemoveFeePayerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSetFeePayer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetFeePayer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetFeePayer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvmFeePayer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvmFeePayer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetFeePayerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetFeePayerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetFeePayerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemoveFeePayer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveFeePayer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveFeePayer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemoveFeePayerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveFeePayerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveFeePayerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
